// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC538LcDvRM0GFf7n4sQ5OY-VQV8iT-3aU',
    appId: '1:51737869661:web:cc33935fcd5bd66fa87cb4',
    messagingSenderId: '51737869661',
    projectId: 'timekeeper-5de46',
    authDomain: 'timekeeper-5de46.firebaseapp.com',
    storageBucket: 'timekeeper-5de46.firebasestorage.app',
    measurementId: 'G-EDVBF4N210',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBMQQaQqsaHvurtoOTeseq7mQd70OJe9M',
    appId: '1:51737869661:android:8fc52f3d8792ed6fa87cb4',
    messagingSenderId: '51737869661',
    projectId: 'timekeeper-5de46',
    storageBucket: 'timekeeper-5de46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAocmpewbZWUk0zX9jXGL7LjtN7lijOJ-0',
    appId: '1:51737869661:ios:69445aea4f96492da87cb4',
    messagingSenderId: '51737869661',
    projectId: 'timekeeper-5de46',
    storageBucket: 'timekeeper-5de46.firebasestorage.app',
    iosClientId: '51737869661-qkppje7ervsp2f0i36g4dpgllqdkv5pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.salvaore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAocmpewbZWUk0zX9jXGL7LjtN7lijOJ-0',
    appId: '1:51737869661:ios:69445aea4f96492da87cb4',
    messagingSenderId: '51737869661',
    projectId: 'timekeeper-5de46',
    storageBucket: 'timekeeper-5de46.firebasestorage.app',
    iosClientId: '51737869661-qkppje7ervsp2f0i36g4dpgllqdkv5pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.salvaore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC538LcDvRM0GFf7n4sQ5OY-VQV8iT-3aU',
    appId: '1:51737869661:web:1df5002d97776229a87cb4',
    messagingSenderId: '51737869661',
    projectId: 'timekeeper-5de46',
    authDomain: 'timekeeper-5de46.firebaseapp.com',
    storageBucket: 'timekeeper-5de46.firebasestorage.app',
    measurementId: 'G-S4T07W4H13',
  );
}
